/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nutrition;

import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author rossy-pc
 */
public class AddUser extends javax.swing.JFrame {

    /**
     * Creates new form AddUser
     */
    public AddUser() {
        initComponents();
        lnametext.setEnabled(false);
        fnametext.setEnabled(false);
        mnametext.setEnabled(false);
        unametext.setEnabled(false);
        passtext.setEnabled(false);
        cpasstext.setEnabled(false);
        birthdate.setEnabled(false);
        fradiobutton.setEnabled(false);
        mradiobutton.setEnabled(false);
        userrole.setEnabled(false);
        SimpleDateFormat dateformat= new SimpleDateFormat("yyyy-MM-dd");
        birthdate.setDateFormat(dateformat);
        birthdate.setText("");
         userrole.insertItemAt("", 0);
         userrole.insertItemAt("Super Administrator", 1);
         userrole.insertItemAt("Administrator", 2);
         userrole.insertItemAt("Editor", 3);
         userrole.insertItemAt("Author", 4);
         userrole.insertItemAt("Contributor", 5);
         userrole.insertItemAt("User", 6);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderradiobuttons = new javax.swing.ButtonGroup();
        topheaderpanel = new javax.swing.JPanel();
        topusernamelabel = new javax.swing.JLabel();
        systemclosebutton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        Headerpanel = new javax.swing.JPanel();
        jPanel49 = new javax.swing.JPanel();
        jLabel223 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        fradiobutton = new javax.swing.JRadioButton();
        mradiobutton = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel167 = new javax.swing.JLabel();
        lnametext = new javax.swing.JTextField();
        jLabel168 = new javax.swing.JLabel();
        fnametext = new javax.swing.JTextField();
        jLabel166 = new javax.swing.JLabel();
        mnametext = new javax.swing.JTextField();
        jLabel171 = new javax.swing.JLabel();
        birthdate = new datechooser.beans.DateChooserCombo();
        jLabel174 = new javax.swing.JLabel();
        unametext = new javax.swing.JTextField();
        jLabel170 = new javax.swing.JLabel();
        jLabel172 = new javax.swing.JLabel();
        cpasstext = new javax.swing.JPasswordField();
        passtext = new javax.swing.JPasswordField();
        jLabel175 = new javax.swing.JLabel();
        userrole = new javax.swing.JComboBox<>();
        jLabel176 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(50, 0));
        setMinimumSize(new java.awt.Dimension(1270, 746));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1270, 746));
        setResizable(false);
        setSize(new java.awt.Dimension(1270, 746));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topheaderpanel.setBackground(new java.awt.Color(203, 221, 255));
        topheaderpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topusernamelabel.setText("User");
        topheaderpanel.add(topusernamelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 60, 20));

        systemclosebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/error.png"))); // NOI18N
        systemclosebutton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        systemclosebutton.setBorderPainted(false);
        systemclosebutton.setContentAreaFilled(false);
        systemclosebutton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        systemclosebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                systemclosebuttonActionPerformed(evt);
            }
        });
        topheaderpanel.add(systemclosebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 0, 40, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-Female Profile-48.png"))); // NOI18N
        topheaderpanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, -4, 50, 50));

        getContentPane().add(topheaderpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 50));

        Headerpanel.setBackground(new java.awt.Color(249, 254, 247));
        Headerpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel49.setBackground(new java.awt.Color(249, 254, 247));
        jPanel49.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(203, 221, 255)));
        jPanel49.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel223.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel223.setText("System Users");
        jPanel49.add(jLabel223, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 20));

        jTable1.setBackground(new java.awt.Color(249, 254, 247));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Userid", "Username", "User Role"
            }
        ));
        jTable1.setRowHeight(20);
        jScrollPane2.setViewportView(jTable1);

        jPanel49.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 580, 590));

        Headerpanel.add(jPanel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 600, 670));

        fradiobutton.setText("Female");
        Headerpanel.add(fradiobutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 270, -1, -1));

        mradiobutton.setText("Male");
        Headerpanel.add(mradiobutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 270, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("AddNew");
        Headerpanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, 50, 20));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("SYSTEM USER");
        Headerpanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, 190, 30));

        jLabel167.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel167.setText("Last Name");
        Headerpanel.add(jLabel167, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, -1, -1));

        lnametext.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lnametext.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        lnametext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnametextActionPerformed(evt);
            }
        });
        Headerpanel.add(lnametext, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 150, 160, 50));

        jLabel168.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel168.setText("First Name");
        Headerpanel.add(jLabel168, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 130, -1, -1));

        fnametext.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fnametext.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        fnametext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnametextActionPerformed(evt);
            }
        });
        Headerpanel.add(fnametext, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 150, 180, 50));

        jLabel166.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel166.setText("Middle Name");
        Headerpanel.add(jLabel166, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 130, -1, -1));

        mnametext.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mnametext.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        Headerpanel.add(mnametext, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 150, 170, 50));

        jLabel171.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel171.setText("Gender");
        Headerpanel.add(jLabel171, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 240, -1, 10));

        birthdate.setCurrentView(new datechooser.view.appearance.AppearancesList("Light",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    birthdate.setCalendarBackground(new java.awt.Color(255, 255, 255));
    birthdate.setNothingAllowed(false);
    birthdate.setLocale(new java.util.Locale("en", "SG", ""));
    birthdate.setNavigateFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11));
    birthdate.setBehavior(datechooser.model.multiple.MultyModelBehavior.SELECT_SINGLE);
    Headerpanel.add(birthdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 260, 300, 50));

    jLabel174.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel174.setText("BirthDate");
    Headerpanel.add(jLabel174, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 240, -1, 10));

    unametext.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    unametext.setDisabledTextColor(new java.awt.Color(255, 255, 255));
    Headerpanel.add(unametext, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 370, 230, 50));

    jLabel170.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel170.setText("User Role");
    Headerpanel.add(jLabel170, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 450, -1, -1));

    jLabel172.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel172.setText("Confirm Password");
    Headerpanel.add(jLabel172, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 450, -1, -1));

    cpasstext.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    cpasstext.setDisabledTextColor(new java.awt.Color(255, 255, 255));
    cpasstext.setMinimumSize(new java.awt.Dimension(2, 20));
    cpasstext.setPreferredSize(new java.awt.Dimension(2, 20));
    cpasstext.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            cpasstextActionPerformed(evt);
        }
    });
    Headerpanel.add(cpasstext, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 480, 290, 50));

    passtext.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    passtext.setDisabledTextColor(new java.awt.Color(255, 255, 255));
    passtext.setMinimumSize(new java.awt.Dimension(2, 20));
    passtext.setPreferredSize(new java.awt.Dimension(2, 20));
    passtext.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            passtextActionPerformed(evt);
        }
    });
    Headerpanel.add(passtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 370, 290, 50));

    jLabel175.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel175.setText("Username");
    Headerpanel.add(jLabel175, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 340, -1, -1));

    userrole.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    userrole.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            userroleActionPerformed(evt);
        }
    });
    Headerpanel.add(userrole, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 480, 240, 50));

    jLabel176.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel176.setText("Password");
    Headerpanel.add(jLabel176, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 340, -1, -1));
    Headerpanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 580, 580, 20));
    Headerpanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, 580, 20));

    jButton1.setText("New");
    jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    jButton1.setContentAreaFilled(false);
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });
    Headerpanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 30, 80, 60));

    jButton2.setText("Clear");
    jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    jButton2.setContentAreaFilled(false);
    jButton2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
        }
    });
    Headerpanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 610, 80, 40));

    jButton3.setText("Save");
    jButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    jButton3.setContentAreaFilled(false);
    jButton3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton3ActionPerformed(evt);
        }
    });
    Headerpanel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 610, 80, 40));

    getContentPane().add(Headerpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1270, 700));

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void systemclosebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_systemclosebuttonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_systemclosebuttonActionPerformed

    private void passtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passtextActionPerformed

    private void cpasstextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpasstextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpasstextActionPerformed

    private void fnametextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnametextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnametextActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        lnametext.setEnabled(true);
        fnametext.setEnabled(true);
        mnametext.setEnabled(true);
        unametext.setEnabled(true);
        passtext.setEnabled(true);
        cpasstext.setEnabled(true);
        birthdate.setEnabled(true);
        fradiobutton.setEnabled(true);
        mradiobutton.setEnabled(true);
        userrole.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        lnametext.setEnabled(false);
            fnametext.setEnabled(false);
            mnametext.setEnabled(false);
            unametext.setEnabled(false);
            passtext.setEnabled(false);
            cpasstext.setEnabled(false);
            birthdate.setEnabled(false);
            fradiobutton.setEnabled(false);
            mradiobutton.setEnabled(false);
            userrole.setEnabled(false);
            
            lnametext.setText("");
            fnametext.setText("");
            mnametext.setText("");
            unametext.setText("");
            passtext.setText("");
            cpasstext.setText("");
            fradiobutton.setSelected(false);
            mradiobutton.setSelected(false);
             birthdate.setText("");
         
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        try{
            
            if(lnametext.getText().isEmpty() && fnametext.getText().isEmpty() && mnametext.getText().isEmpty() && passtext.getText().length()==0 && cpasstext.getText().length()==0 && unametext.getText().isEmpty() && !fradiobutton.isSelected() && !mradiobutton.isSelected() &&  birthdate.getText().isEmpty()&& userrole.getSelectedItem().equals("")){
             JOptionPane.showMessageDialog(null,"Empty Fields","Access Denied",JOptionPane.ERROR_MESSAGE);
            }
            
            else if(lnametext.getText().isEmpty() || fnametext.getText().isEmpty() || mnametext.getText().isEmpty() || passtext.getText().length()==0 || cpasstext.getText().length()==0 || unametext.getText().isEmpty() || !fradiobutton.isSelected() && !mradiobutton.isSelected() ||birthdate.getText().isEmpty()|| userrole.getSelectedItem().equals("")){
             JOptionPane.showMessageDialog(null,"Empty Fields","Access Denied",JOptionPane.ERROR_MESSAGE);
             
               
            }
            
            else{
            JOptionPane.showMessageDialog(null,"Choko na!","OK na",JOptionPane.INFORMATION_MESSAGE);
            lnametext.setEnabled(false);
            fnametext.setEnabled(false);
            mnametext.setEnabled(false);
            unametext.setEnabled(false);
            passtext.setEnabled(false);
            cpasstext.setEnabled(false);
            birthdate.setEnabled(false);
            fradiobutton.setEnabled(false);
            mradiobutton.setEnabled(false);
            userrole.setEnabled(false);
            
            lnametext.setText("");
            fnametext.setText("");
            mnametext.setText("");
            unametext.setText("");
            passtext.setText("");
            cpasstext.setText("");
            fradiobutton.setSelected(false);
            mradiobutton.setSelected(false);
            birthdate.setText("");
            
         

            }
        
        
        }
        catch (Exception e)
        {System.err.print(e);}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void userroleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userroleActionPerformed
        // TODO add your handling code here:
  
    }//GEN-LAST:event_userroleActionPerformed

    private void lnametextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnametextActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_lnametextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddUser().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Headerpanel;
    private datechooser.beans.DateChooserCombo birthdate;
    private javax.swing.JPasswordField cpasstext;
    private javax.swing.JTextField fnametext;
    private javax.swing.JRadioButton fradiobutton;
    private javax.swing.ButtonGroup genderradiobuttons;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel166;
    private javax.swing.JLabel jLabel167;
    private javax.swing.JLabel jLabel168;
    private javax.swing.JLabel jLabel170;
    private javax.swing.JLabel jLabel171;
    private javax.swing.JLabel jLabel172;
    private javax.swing.JLabel jLabel174;
    private javax.swing.JLabel jLabel175;
    private javax.swing.JLabel jLabel176;
    private javax.swing.JLabel jLabel223;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField lnametext;
    private javax.swing.JTextField mnametext;
    private javax.swing.JRadioButton mradiobutton;
    private javax.swing.JPasswordField passtext;
    public javax.swing.JButton systemclosebutton;
    private javax.swing.JPanel topheaderpanel;
    private javax.swing.JLabel topusernamelabel;
    private javax.swing.JTextField unametext;
    private javax.swing.JComboBox<String> userrole;
    // End of variables declaration//GEN-END:variables
}
