/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nutrition;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
/**
 *
 * @author User
 */
public class mainform extends javax.swing.JFrame {

    
    /**
     * Creates new form index
     */
    public mainform() {
        initComponents();
      
     
      
       
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menupanel = new javax.swing.JPanel();
        Homebutton = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        addrecordbutton = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        topheaderpanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        systemclosebutton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        Headerpanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Homepanel = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        homebackbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(229, 238, 255));
        setLocation(new java.awt.Point(50, 0));
        setMinimumSize(new java.awt.Dimension(1260, 700));
        setName("mainform"); // NOI18N
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1260, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menupanel.setBackground(new java.awt.Color(0, 18, 50));

        Homebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        Homebutton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Homebutton.setBorderPainted(false);
        Homebutton.setContentAreaFilled(false);
        Homebutton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Homebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomebuttonActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/settings.png"))); // NOI18N
        jButton7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        addrecordbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new-file.png"))); // NOI18N
        addrecordbutton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        addrecordbutton.setBorderPainted(false);
        addrecordbutton.setContentAreaFilled(false);
        addrecordbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addrecordbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addrecordbuttonActionPerformed(evt);
            }
        });

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/head.png"))); // NOI18N
        jButton9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/newspaper.png"))); // NOI18N
        jButton10.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menupanelLayout = new javax.swing.GroupLayout(menupanel);
        menupanel.setLayout(menupanelLayout);
        menupanelLayout.setHorizontalGroup(
            menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menupanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addrecordbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Homebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        menupanelLayout.setVerticalGroup(
            menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menupanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(Homebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(addrecordbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        getContentPane().add(menupanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 90, 650));

        topheaderpanel.setBackground(new java.awt.Color(203, 221, 255));
        topheaderpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        topheaderpanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, -6, 30, 50));

        jLabel5.setText("User");
        topheaderpanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 60, 20));

        systemclosebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/error.png"))); // NOI18N
        systemclosebutton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        systemclosebutton.setBorderPainted(false);
        systemclosebutton.setContentAreaFilled(false);
        systemclosebutton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        systemclosebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                systemclosebuttonActionPerformed(evt);
            }
        });
        topheaderpanel.add(systemclosebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 0, 40, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-Female Profile-48.png"))); // NOI18N
        topheaderpanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, -4, 50, 50));

        getContentPane().add(topheaderpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 50));

        Headerpanel.setBackground(new java.awt.Color(249, 254, 247));
        Headerpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 52)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 18, 50));
        jLabel2.setText("HEALTH EQUITY INFORMATION SYSTEM");
        Headerpanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 950, 60));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 18, 50));
        jLabel3.setText("COMPOSTELA VALLEY PROVINCE");
        Headerpanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 570, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/comval.png"))); // NOI18N
        jLabel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Headerpanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 170));

        Homepanel.setBackground(new java.awt.Color(249, 254, 247));
        Homepanel.setDoubleBuffered(false);
        Homepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/maintenance.png"))); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.setContentAreaFilled(false);
        Homepanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 40, 210, 220));

        jButton6.setForeground(new java.awt.Color(32, 47, 90));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/adduser.png"))); // NOI18N
        jButton6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton6.setContentAreaFilled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        Homepanel.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 210, 220));

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view.png"))); // NOI18N
        jButton12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton12.setContentAreaFilled(false);
        Homepanel.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 210, 220));

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/text-lines.png"))); // NOI18N
        jButton13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton13.setContentAreaFilled(false);
        Homepanel.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, 210, 220));

        jLabel1.setText("Settings");
        Homepanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 270, 50, 20));

        jLabel6.setText("Add Child Record");
        Homepanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 100, 20));

        jLabel7.setText("View Child Record");
        Homepanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 110, 20));

        jLabel9.setText("Reports");
        Homepanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 270, 50, 20));

        homebackbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/left-arrow.png"))); // NOI18N
        homebackbutton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        homebackbutton.setBorderPainted(false);
        homebackbutton.setContentAreaFilled(false);
        homebackbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        homebackbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebackbuttonActionPerformed(evt);
            }
        });
        Homepanel.add(homebackbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 400, 40, 40));

        Headerpanel.add(Homepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 1150, 440));

        getContentPane().add(Headerpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 1170, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomebuttonActionPerformed
        // TODO add your handling code here:
        
       Homepanel.setVisible(true);
    
       Homebutton.setVisible(false);
    }//GEN-LAST:event_HomebuttonActionPerformed

    private void homebackbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebackbuttonActionPerformed
        // TODO add your handling code here:
       
       Homepanel.setVisible(false);
       Homebutton.setVisible(true);
    }//GEN-LAST:event_homebackbuttonActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void addrecordbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addrecordbuttonActionPerformed
        // TODO add your handling code here:
       
         addchildrecord w = new addchildrecord();
                    w.setVisible(true);
                     this.dispose();
    }//GEN-LAST:event_addrecordbuttonActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
   
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void systemclosebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_systemclosebuttonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_systemclosebuttonActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainform().setVisible(true);
                
                
             
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Headerpanel;
    public javax.swing.JButton Homebutton;
    private javax.swing.JPanel Homepanel;
    public javax.swing.JButton addrecordbutton;
    public javax.swing.JButton homebackbutton;
    public javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    public javax.swing.JButton jButton7;
    public javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel menupanel;
    public javax.swing.JButton systemclosebutton;
    private javax.swing.JPanel topheaderpanel;
    // End of variables declaration//GEN-END:variables
}
